### PR TITLE
Clarifying how jobs run in Singularity containers

### PR DESCRIPTION
**Pull request by eharstad**

### CODE REVIEW

**Comment by lmichael107** [comment]
I made some tweaks. Look good @eharstad ?

**Comment by eharstad** [comment]
Yes, looks good @lmichael107

**Comment by lmichael107** [comment]
Great. Take a look in the final form to make sure everything looks good? @eharstad

**Comment by eharstad** [comment]
Looks good at least in the github rendering @lmichael107

**Pull request merged**
