### PR TITLE
Adding upcoming dates to training page

### PR DESCRIPTION
**Pull request by ChristinaLK**

### CODE REVIEW

**Comment by ChristinaLK** [comment]
Comments / suggestion on format and shared information would be great!

**Comment by ChristinaLK** [comment]
Suggestion from Rachel
```
### New User Training
* [Date]() - [Register]()
* [Date]() - [Register]()

### Topic of the Month: Topic Name
* [Date]() - [Register]()
```

**Review by lmichael107 — COMMENTED** [review]
As discussed, please lead by topic (not date) and note something like "Most recently delivered on XXXX" to indicate dates.

**Comment by ChristinaLK** [comment]
@lmichael107 and @rachellombardi can you review the latest version?

**Pull request merged**
